nav:
  Home: /
  Topic: /topic/
  About: /about/
  #Writing: /posts/
  #Projects: http://github.com/sergodeeva

projects_url: https://mrjk.netlify.app/

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/JK.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/JK.ico
        gravatar: false
      android:
        url: /images/JK.ico
        gravator: false
      apple:
        url: /images/JK.ico
        gravator: false
    social_links:
        #github: http://github.com/sergodeeva
        #facebook: /
        #linkedin: https://www.linkedin.com/in/natalyakosenko/
    show_all_posts: true
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: mrjk-1 # Disqus Comments Shortname
    google_analytics: 6271886117 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
